import json
import logging
from typing import Dict, Any, Tuple
from app.core.config import settings

logger = logging.getLogger(__name__)

# Pre-compiled common Manglish mapping dictionary for high performance
MANGLISH_INTENT_MAP = {
    "license puthukkanam": "renew driving licence",
    "driving license puthukkanam": "renew driving licence",
    "dl renewal": "renew driving licence",
    "licence renew": "renew driving licence",
    "laisenso puthukkanam": "renew driving licence",
    "license edukkanam": "driving licence",
    "puthiya license": "driving licence",
    "learner's license": "learner's licence",
    "learners license": "learner's licence",
    "learners test": "learner's licence",
    "aadhaar update": "aadhaar update",
    "aadhaar card change": "aadhaar update",
    "pan card": "pan card",
    "pan edukkanam": "pan card",
    "passport edukkanam": "passport",
    "pass port": "passport",
    "birth certificate": "birth certificate",
    "janana certificate": "birth certificate",
    "death certificate": "death certificate",
    "marana certificate": "death certificate",
    "income certificate": "income certificate",
    "varamana certificate": "income certificate",
    "community certificate": "community certificate",
    "jaathi certificate": "community certificate",
    "residence certificate": "residence certificate",
    "thalamasam certificate": "residence certificate",
    "ration card": "ration card",
    "ration card maattanum": "ration card",
    "voter id": "voter id",
    "vote card": "voter id",
    "pension": "pension schemes",
    "ksrtc concession": "welfare schemes",
    "vehicle registration": "vehicle registration",
    "vandi registration": "vehicle registration",
    "vehicle transfer": "vehicle transfer",
    "vandi maattal": "vehicle transfer"
}

class AIService:
    def __init__(self):
        self.api_key = settings.GEMINI_API_KEY
        self.client = None
        if self.api_key:
            try:
                from google import genai
                self.client = genai.Client(api_key=self.api_key)
            except Exception as e:
                logger.warning(f"Could not initialize Gemini Client: {e}")

    def detect_language_and_intent(self, text_query: str) -> Tuple[str, str, str]:
        """
        Detects language ('ml', 'en', 'manglish'), standard intent, and translated English search query.
        """
        clean_text = text_query.strip().lower()

        # Check Manglish map first
        for key, intent in MANGLISH_INTENT_MAP.items():
            if key in clean_text:
                return "manglish", intent, intent

        # Unicode detection for Malayalam characters (\u0D00 to \u0D7F)
        has_malayalam = any("\u0d00" <= char <= "\u0d7f" for char in text_query)
        detected_lang = "ml" if has_malayalam else "en"

        # Try Gemini API if available
        if self.client:
            try:
                prompt = (
                    "You are an NLP analyzer for Indian & Kerala government service requests.\n"
                    f"Analyze query: '{text_query}'.\n"
                    "Return ONLY valid JSON with keys:\n"
                    "- language: 'ml', 'en', or 'manglish'\n"
                    "- canonical_intent: string short service name (e.g. 'passport', 'renew driving licence', 'income certificate')\n"
                    "- search_keywords_en: English query string\n"
                )
                response = self.client.models.generate_content(
                    model="gemini-2.5-flash",
                    contents=prompt
                )
                content = response.text.strip()
                if "```json" in content:
                    content = content.split("```json")[1].split("```")[0].strip()
                data = json.loads(content)
                return data.get("language", detected_lang), data.get("canonical_intent", text_query), data.get("search_keywords_en", text_query)
            except Exception as e:
                logger.warning(f"Gemini API intent resolution fallback triggered: {e}")

        return detected_lang, text_query, text_query

    def format_factual_response(self, service_facts: Dict[str, Any], lang: str = "en") -> str:
        """
        Formats structured database facts into a clear, natural WhatsApp markdown message in user's language.
        No facts are generated by AI.
        """
        is_ml = lang == "ml" or lang == "manglish"

        if is_ml:
            header = f"🏛️ *{service_facts['service_name']}*\n{service_facts['description']}\n"
            req_docs = "\n".join(service_facts['documents']) if service_facts['documents'] else "പ്രത്യേക രേഖകൾ ആവശ്യമില്ല"
            guides = "\n\n".join(service_facts['guides']) if service_facts['guides'] else "ഘട്ടങ്ങൾ ലഭ്യമല്ല"
            
            body = (
                f"{header}\n"
                f"📋 *ആവശ്യമായ രേഖകൾ (Required Documents):*\n{req_docs}\n\n"
                f"💰 *അപേക്ഷാ ഫീസ് (Fees):* {service_facts['fees']}\n"
                f"⏱️ *പ്രോസസ്സിംഗ് സമയം (Time):* {service_facts['processing_time']}\n"
                f"🏢 *ഓഫീസ് (Office):* {service_facts['office_type']}\n"
                f"🌐 *ഔദ്യോഗിക വെബ്സൈറ്റ് (Website):* {service_facts['official_website']}\n\n"
                f"📝 *അപേക്ഷിക്കുന്ന വിധം (Guide):*\n{guides}\n\n"
                f"💡 കൂടുതൽ വിവരങ്ങൾക്ക് 'Checklist' എന്ന് ടൈപ്പ് ചെയ്യുക."
            )
        else:
            header = f"🏛️ *{service_facts['service_name']}*\n{service_facts['description']}\n"
            req_docs = "\n".join(service_facts['documents']) if service_facts['documents'] else "No special documents required"
            guides = "\n\n".join(service_facts['guides']) if service_facts['guides'] else "Steps unavailable"

            body = (
                f"{header}\n"
                f"📋 *Required Documents:*\n{req_docs}\n\n"
                f"💰 *Application Fee:* {service_facts['fees']}\n"
                f"⏱️ *Processing Time:* {service_facts['processing_time']}\n"
                f"🏢 *Office:* {service_facts['office_type']}\n"
                f"🌐 *Official Website:* {service_facts['official_website']}\n\n"
                f"📝 *Step-by-Step Guide:*\n{guides}\n\n"
                f"💡 Type 'Checklist' to test your document readiness."
            )

        return body

ai_service = AIService()
